language: python
env:
  matrix:
  - PYTHON="python=2.7"
  - PYTHON="python=3.4"
  global:
  - GH_REF: github.com/metabolite-atlas/metatlas.git
  - secure: HCQ8gC9b17rPuF4/KnZFlh3crLhlRFKtbUMVJGFuCnz4r7Zna1TELWgmLI0WX6jGgwjjO9ca5aKOOKj0CVGvOPTmIX3VCGEehgxfN0K9pdE9eUlaN047hh32CrTxtik97jxImvPnbni/QmwI3/xI/XrPj2U5iUm38h/WDg+sTPU=
before_install:
- openssl aes-256-cbc -K $encrypted_10f2d1413fc4_key -iv $encrypted_10f2d1413fc4_iv
  -in kb_auth_encrypted.dat -out kb_auth_do_not_commit.dat -d
- export KB_AUTH_TOKEN=`cat kb_auth_do_not_commit.dat`
- sudo apt-add-repository "deb http://cran.stat.ucla.edu/bin/linux/ubuntu precise/"
- sudo apt-get update
- sudo apt-get install --force-yes libnetcdf-dev netcdf-bin r-base
- export MPL_DIR=$HOME/.config/matplotlib
- mkdir -p $MPL_DIR
- touch $MPL_DIR/matplotlibrc
- echo "backend:Template" > $MPL_DIR/matplotlibrc
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes
- conda update conda
- conda info -a
- travis_retry conda create -n test $PYTHON pip nose pytables matplotlib pandas jupyter
- source activate test
- rm /home/travis/miniconda/envs/test/lib/libreadline.so.6
- travis_retry pip install coveralls requests_toolbelt rpy2
- sudo Rscript scripts/xcms-install.R
- conda install -c https://conda.anaconda.org/rdkit rdkit
install:
- export PYTHONWARNINGS=all
- pip install -e .
script:
- if [[ $PYTHON == python=3.4* ]]; then nosetests --exe -v --with-doctest --with-cov
  --cover-package metatlas; else nosetests --exe -v metatlas; fi
- make docs
after_success:
- coveralls
- if [[ $PYTHON == python=3.4* ]]; then bash scripts/travis_after_success.sh; fi
